[tool.ruff]
line-length = 120
extend-include = ["*.pyt"]
[tool.ruff.lint]
ignore = ["E501"]
[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests", "src"]
norecursedirs = [".env", "data", "maps", ".github", ".vscode"]
console_output_style = "count"
addopts = "--cov-branch --cov=src.main --cov-report term --cov-report xml:cov.xml --instafail"
